export interface PackageSeed {
  code: string;
  serviceTypeCode: string;
  name: string;
  kind: 'STANDARD' | 'ADD_ON' | 'CUSTOM_TEMPLATE';
  description: string;
  specifications: Record<string, string | number | boolean>;
  terms: ReadonlyArray<{ termMonths: number; currency: 'JOD'; standardSellingPrice: string }>;
}

const terms = (...entries: ReadonlyArray<[number, string]>) =>
  entries.map(([termMonths, standardSellingPrice]) => ({
    termMonths,
    currency: 'JOD' as const,
    standardSellingPrice,
  }));

export const packageCatalogSeeds: ReadonlyArray<PackageSeed> = [
  {
    code: 'HOSTING_CUSTOM_400GB',
    serviceTypeCode: 'HOSTING',
    name: 'Custom PLAN 400GB',
    kind: 'STANDARD',
    description: '50GB web, 350GB mail, unlimited email, 500GB transfer, one domain.',
    specifications: {
      webSpaceGb: 50,
      mailSpaceGb: 350,
      emailAccounts: 'Unlimited',
      monthlyTransferGb: 500,
      domainRegistrations: 1,
    },
    terms: terms([12, '1150.000'], [36, '2500.000']),
  },
  {
    code: 'HOSTING_CUSTOM_250GB',
    serviceTypeCode: 'HOSTING',
    name: 'Custom PLAN 250GB',
    kind: 'STANDARD',
    description: '50GB web, 200GB mail, unlimited email, 500GB transfer, one domain.',
    specifications: {
      webSpaceGb: 50,
      mailSpaceGb: 200,
      emailAccounts: 'Unlimited',
      monthlyTransferGb: 500,
      domainRegistrations: 1,
    },
    terms: terms([12, '950.000'], [36, '1995.000']),
  },
  {
    code: 'HOSTING_CUSTOM_100GB',
    serviceTypeCode: 'HOSTING',
    name: 'Custom PLAN 100GB',
    kind: 'STANDARD',
    description: '50GB web, 100GB mail, unlimited email, 500GB transfer, one domain.',
    specifications: {
      webSpaceGb: 50,
      mailSpaceGb: 100,
      emailAccounts: 'Unlimited',
      monthlyTransferGb: 500,
      domainRegistrations: 1,
    },
    terms: terms([12, '775.000'], [36, '1675.000']),
  },
  {
    code: 'HOSTING_DIAMOND',
    serviceTypeCode: 'HOSTING',
    name: 'DIAMOND PLAN',
    kind: 'STANDARD',
    description: '50GB web, 40GB mail, unlimited email, 500GB transfer, one domain.',
    specifications: {
      webSpaceGb: 50,
      mailSpaceGb: 40,
      emailAccounts: 'Unlimited',
      monthlyTransferGb: 500,
      domainRegistrations: 1,
    },
    terms: terms([12, '625.000'], [36, '1370.000']),
  },
  {
    code: 'HOSTING_PLATINUM',
    serviceTypeCode: 'HOSTING',
    name: 'PLATINUM PLAN',
    kind: 'STANDARD',
    description: '50GB web, 20GB mail, unlimited email, 500GB transfer, one domain.',
    specifications: {
      webSpaceGb: 50,
      mailSpaceGb: 20,
      emailAccounts: 'Unlimited',
      monthlyTransferGb: 500,
      domainRegistrations: 1,
    },
    terms: terms([12, '400.000'], [36, '890.000']),
  },
  {
    code: 'HOSTING_PREMIUM',
    serviceTypeCode: 'HOSTING',
    name: 'PREMIUM PLAN',
    kind: 'STANDARD',
    description: '30GB web, 8GB mail, unlimited email, 250GB transfer, one domain.',
    specifications: {
      webSpaceGb: 30,
      mailSpaceGb: 8,
      emailAccounts: 'Unlimited',
      monthlyTransferGb: 250,
      domainRegistrations: 1,
    },
    terms: terms([12, '250.000'], [36, '525.000']),
  },
  {
    code: 'SSL_SINGLE',
    serviceTypeCode: 'SSL',
    name: 'SSL Certificate',
    kind: 'STANDARD',
    description: 'Single-domain validated SSL certificate.',
    specifications: {
      validation: 'single-domain',
      warrantyUsd: 10000,
      includesInstallationTool: true,
    },
    terms: terms([12, '185.000'], [36, '250.000'], [60, '350.000']),
  },
  {
    code: 'SSL_WILDCARD',
    serviceTypeCode: 'SSL',
    name: 'SSL Certificate Wild',
    kind: 'STANDARD',
    description: 'Domain and subdomain validated wildcard SSL certificate.',
    specifications: {
      validation: 'domain-and-subdomain',
      warrantyUsd: 10000,
      includesInstallationTool: true,
    },
    terms: terms([12, '300.000'], [36, '750.000'], [60, '1150.000']),
  },
  {
    code: 'DEDICATED_LINUX_8X',
    serviceTypeCode: 'DEDICATED_SERVER',
    name: '8X Power - LINUX',
    kind: 'STANDARD',
    description: 'Xlarge Linux cloud dedicated server.',
    specifications: {
      operatingSystem: 'Linux',
      ramGb: 8,
      cpuCores: 4,
      storageSsdGb: 50,
      firewall: true,
    },
    terms: terms([12, '1650.000'], [36, '3450.000']),
  },
  {
    code: 'DEDICATED_LINUX_4X',
    serviceTypeCode: 'DEDICATED_SERVER',
    name: '4X Power - LINUX',
    kind: 'STANDARD',
    description: 'Medium Linux cloud dedicated server.',
    specifications: {
      operatingSystem: 'Linux',
      ramGb: 4,
      cpuCores: 2,
      storageSsdGb: 50,
      firewall: true,
    },
    terms: terms([12, '950.000'], [36, '1990.000']),
  },
  {
    code: 'DEDICATED_LINUX_2X',
    serviceTypeCode: 'DEDICATED_SERVER',
    name: '2X Power - LINUX',
    kind: 'STANDARD',
    description: 'Small Linux cloud dedicated server.',
    specifications: {
      operatingSystem: 'Linux',
      ramGb: 2,
      cpuCores: 1,
      storageSsdGb: 50,
      firewall: true,
    },
    terms: terms([12, '700.000'], [36, '1620.000']),
  },
  {
    code: 'DEDICATED_WINDOWS_8X',
    serviceTypeCode: 'DEDICATED_SERVER',
    name: '8X Power - WINDOWS',
    kind: 'STANDARD',
    description: 'Xlarge Windows cloud dedicated server.',
    specifications: {
      operatingSystem: 'Windows',
      ramGb: 8,
      cpuCores: 4,
      storageSsdGb: 50,
      firewall: true,
    },
    terms: terms([12, '2350.000'], [36, '5150.000']),
  },
  {
    code: 'DEDICATED_WINDOWS_4X',
    serviceTypeCode: 'DEDICATED_SERVER',
    name: '4X Power - WINDOWS',
    kind: 'STANDARD',
    description: 'Medium Windows cloud dedicated server.',
    specifications: {
      operatingSystem: 'Windows',
      ramGb: 4,
      cpuCores: 2,
      storageSsdGb: 50,
      firewall: true,
    },
    terms: terms([12, '1450.000'], [36, '3100.000']),
  },
  {
    code: 'DEDICATED_WINDOWS_2X',
    serviceTypeCode: 'DEDICATED_SERVER',
    name: '2X Power - WINDOWS',
    kind: 'STANDARD',
    description: 'Small Windows cloud dedicated server.',
    specifications: {
      operatingSystem: 'Windows',
      ramGb: 2,
      cpuCores: 1,
      storageSsdGb: 50,
      firewall: true,
    },
    terms: terms([12, '1100.000'], [36, '2500.000']),
  },
  {
    code: 'ADDON_EXTRA_SECURITY',
    serviceTypeCode: 'DEDICATED_SERVER',
    name: 'Extra Security',
    kind: 'ADD_ON',
    description: 'SSL certificate add-on for dedicated packages.',
    specifications: {
      includes: 'SSL Certificate',
      threeYearIncludedWith: '4X or 8X three-year plan',
    },
    terms: terms([12, '185.000'], [36, '250.000']),
  },
  {
    code: 'ADDON_EXTRA_EMAIL',
    serviceTypeCode: 'DEDICATED_SERVER',
    name: 'Extra Email',
    kind: 'ADD_ON',
    description: '8GB email space with unlimited email accounts.',
    specifications: {
      mailSpaceGb: 8,
      emailAccounts: 'Unlimited',
      threeYearIncludedWith: '4X or 8X three-year plan',
    },
    terms: terms([12, '250.000'], [36, '420.000']),
  },
  {
    code: 'SUPPORT_PLATINUM',
    serviceTypeCode: 'SUPPORT',
    name: 'PLATINUM SUPPORT PLAN',
    kind: 'STANDARD',
    description: '48 VIP support tickets; each request up to two A4 dynamic HTML pages.',
    specifications: { tickets: 48, vip: true, responseHoursLessThan: 48, expiresAfterMonths: 12 },
    terms: terms([12, '975.000'], [36, '1800.000']),
  },
  {
    code: 'SUPPORT_PREMIUM',
    serviceTypeCode: 'SUPPORT',
    name: 'PREMIUM SUPPORT PLAN',
    kind: 'STANDARD',
    description: '36 VIP support tickets; each request up to two A4 dynamic HTML pages.',
    specifications: { tickets: 36, vip: true, responseHoursLessThan: 48, expiresAfterMonths: 12 },
    terms: terms([12, '750.000'], [36, '1380.000']),
  },
  {
    code: 'SUPPORT_PROFESSIONAL',
    serviceTypeCode: 'SUPPORT',
    name: 'PROFESSIONAL SUPPORT PLAN',
    kind: 'STANDARD',
    description: '24 support tickets; each request up to two A4 dynamic HTML pages.',
    specifications: { tickets: 24, vip: false, expiresAfterMonths: 12 },
    terms: terms([12, '550.000'], [36, '1175.000']),
  },
  ...(
    [
      ['DOMAIN', 'Domain'],
      ['SSL', 'SSL'],
      ['HOSTING', 'Hosting'],
      ['DEDICATED_SERVER', 'Dedicated Server'],
      ['SUPPORT', 'Support'],
      ['ANTIVIRUS', 'Antivirus'],
      ['DNS_HOSTING', 'DNS Hosting'],
      ['APP_SUBSCRIPTION', 'App Subscription'],
    ] as const
  ).map(([serviceTypeCode, name]) => ({
    code: `CUSTOM_${serviceTypeCode}`,
    serviceTypeCode,
    name: `Custom (${name})`,
    kind: 'CUSTOM_TEMPLATE' as const,
    description: `Human-approved custom ${name.toLowerCase()} subscription.`,
    specifications: {},
    terms: [],
  })),
];
